### ISSUE TITLE
Upgrade BSP to LF6.6.3_1.0.0

### ISSUE THREAD

**Issue by MrCry0** [Freescale/meta-freescale#1777]
The immediate items to work on are:

- [x]  Upgrade Linux kernel and headers (i.MX variants) 
  - #1785 
- [x]  Upgrade Linux kernel (FSLC forks i.MX variants)
  - #1782 
  - #1783 
  - #1785 
- [x]  Upgrade U-Boot (FSLC forks i.MX variants)
  - #1786 
  - #1787 
- [x]  Upgrade OP-TEE
  - https://github.com/Freescale/meta-freescale/pull/1789
- [x]  Upgrade ATF (i.MX variants)
  - https://github.com/Freescale/meta-freescale/pull/1790
- [x]  Upgrade Multimedia Packages #1779 
- [x]  Upgrade Graphics Packages #1803 
- [x]  Upgrade Jailhouse
  - https://github.com/Freescale/meta-freescale/pull/1794
- [x]  Upgrade mcore-demos
  - https://github.com/Freescale/meta-freescale/pull/1795
- [x]  Upgrade firmware-imx*
  - https://github.com/Freescale/meta-freescale/pull/1792
  - https://github.com/Freescale/meta-freescale/pull/1793
- [x]  Upgrade imx-mkimage
  - https://github.com/Freescale/meta-freescale/pull/1792

The Release Notes are [here](https://www.nxp.com/docs/en/release-note/IMX_LINUX_RELEASE_NOTES.pdf) for checking.

**Comment by angolini** [comment]
From the SCR it looks like we have some new packages:

- imx-sm.git
- imx-oei.git
- crypto-af-alg.git
- mali-imx-r47.0-b867f39.bin
- imx95-m7-demo-2.15.000.bin
- imx93-m33-demo-2.15.000.bin
- neutron.git
- tflite-neutron-delegate.git

There are other packages that are not yet upstreamed, basically because they are demos or based on cortex M. I don't know how critical they are. I'm only pointing out some new packages to review.

**Comment by MrCry0** [comment]
I'm working on u-boot, optee and atf

**Comment by tprrt** [comment]
Hello,

It is seems there is a regression on i.MX93:
```
[    1.470460] tee_client_open_session failed, err: ffff000c
[    1.475883] TEE-Crypto: Init failed[0xffffffea].
```

Moreover https://github.com/Freescale/meta-freescale/pull/1809.

Kind regards,
Thomas Perrot

**Comment by angolini** [comment]
It looks like this issue is completed and can be closed
