### ISSUE TITLE
gtk+3_%.bbappend causes build failure

### ISSUE THREAD

**Issue by cdgarren** [Freescale/meta-freescale#27]
The bbappend for gtk+3 is causing chromium-x11 to fail. It relies on the gtk x11 headers to be present, but this removes x11 from the distro features, and causes the headers to not be generated. Commenting out the bbappend contents allows the build to succeed.

**Comment by otavio** [comment]
Which machine and distro did you use?

**Comment by cdgarren** [comment]
Machine is var-som-mx6, and distro is poky. I was using the imx7-var-som and was able to build successfully.

**Comment by otavio** [comment]
Which branch?

**Comment by cdgarren** [comment]
I'm on the sumo branch.

**Comment by thochstein** [comment]
Originally the bbappend disabled Wayland backend if x11 was in the distro. Since we now use Wayland backend for i.MX GPU if both wayland and x11 are in the distro, the disablement was reversed. I don't know  the ramifications of dropping the x11 disablement. I'll try to ask Prabhu. Is it possible to use a Wayland version of chromium instead?

**Comment by cdgarren** [comment]
My schedule doesn't allow time to work on using chromium-wayland. One suggestion I have is to possibly warn or error if both distro features are enabled, instead of silently removing one.

**Comment by otavio** [comment]
Any news on this side? otherwise I will close this.

**Comment by otavio** [comment]
Close due inactiveness.
